[frontend]
frontend.rachanadev.online
[mysql]
mysql.rachanadev.online
[backend]
backend.rachanadev.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
# i gave the variables for all hosts here.